name: Check for updates on ticketing page

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8-22 * * *

jobs:
  check_for_update:
    runs-on: ubuntu-latest
    outputs:
      lines_of_diff: ${{ steps.check_diff.outputs.lines_of_diff}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check diff with last stored version
        id: check_diff
        run: |
          curl https://final2024bilbao.com/en/buy-your-ticket | cat >> current.html
          sed -i -r 's/href="\/cdn-cgi\/l\/email-protection#[a-z0-9]+"//g' current.html
          sed -i -r 's/href="\/cdn-cgi\/l\/email-protection#[a-z0-9]+"//g' buy-your-ticket.html
          sed -i -r 's/data-cfemail="[a-z0-9]+"//g' current.html
          sed -i -r 's/data-cfemail="[a-z0-9]+"//g' buy-your-ticket.html
          
          LINES_OF_DIFF=$(diff current.html buy-your-ticket.html | wc -l)
          
          echo "Found ${LINES_OF_DIFF} lines of diff"
          
          echo "lines_of_diff=$LINES_OF_DIFF" >> "$GITHUB_OUTPUT"
  notify_telegram_bot:
    # if: ${{ needs.check_for_update.outputs.lines_of_diff != '0' }}
    runs-on: ubuntu-latest
    needs:
      - check_for_update
    steps:
      - name: Notify Telegram RoadToBilbaoBot for Frauke
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Schnell Tickets kaufen!!!
            https://final2024bilbao.com/en/buy-your-ticket
      - name: Notify Telegram RoadToBilbaoBot for Ulli
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
          message: |
            Schnell Tickets kaufen!!!
            https://final2024bilbao.com/en/buy-your-ticket
